---
layout : post
title: "Shiny_study_1"
subtitle: "Lesson_1"
author: "ooDoo"
date: 2018-03-07
categories : study
cover : /assets/article_images/title/instacode_sizedown.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. INSTALL SHINY
```{r}
# install.packages("shiny")
library(shiny)
```
```{r}
# runExample("01_hello")
```
source : https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/


# 2. [app.R]'s 3_components
 •a user interface object (`ui`)
 : controls the layout and appearance of your app
  
 •a `server` function
 : contains the instructions that your computer needs to build your app.

 •a call to the `shinyApp` function
 : creates Shiny app objects from an explicit UI/server pair.


## 1) ui
: the ui object for the Hello Shiny example.
```{r}
# Define UI for app that draws a histogram ----
ui <- fluidPage(

  # App title ----
  titlePanel("Hello Shiny!"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input: Slider for the number of bins ----
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Histogram ----
      plotOutput(outputId = "distPlot")

    )
  )
)
```

## 2) server
: the server function for the Hello Shiny example.
```{r}
# Define server logic required to draw a histogram ----
server <- function(input, output) {

  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  # This expression that generates a histogram is wrapped in a call
  # to renderPlot to indicate that:
  #
  # 1. It is "reactive" and therefore should be automatically
  #    re-executed when inputs (input$bins) change
  # 2. Its output type is a plot
  output$distPlot <- renderPlot({

    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)

    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "Waiting time to next eruption (in mins)",
         main = "Histogram of waiting times")

    })

}
```

## 3) shinyApp 
```{r}
# shinyApp(ui = ui, server = server)
```
*app.R이 작동하고 있는 도중에는 R session이 작동하지 않음.*



```{r}
# runExample("06_tabsets")
```







